# Generated by Django 4.2.4 on 2023-09-23 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='data_last_modified',
            field=models.DateField(auto_now_add=True, verbose_name='дата последнего изменения'),
        ),
    ]
