# Generated by Django 4.2.4 on 2023-09-24 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_product_data_last_modified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='version',
            name='products',
        ),
        migrations.AddField(
            model_name='version',
            name='product',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='version',
            name='is_active',
            field=models.BooleanField(verbose_name='признак текущей версии'),
        ),
    ]
